language: java
jdk: openjdk8
install: echo "skip 'gradle assemble' step"
jobs:
  include:
    - stage: "build and deploy to staging"
      script:
        - echo "*** BUILDING ***"
        - ./gradlew :webapp:build
        - echo "*** CREATING ARTIFACT ***"
        - ./gradlew :webapp:shadowJar
        - echo "*** DEPLOYING TO STAGING ***"
        - HEROKU_API_KEY="$HEROKU_API_KEY"
        - heroku plugins:install java
        - heroku deploy:jar webapp/build/libs/cmh-webapp-demo.jar --app cmh-webapp-demo-staging
    - stage: "smoke test staging deployment"
      env:
        - SMOKE_TEST_ENDPOINT="https://cmh-webapp-demo-staging.herokuapp.com"
      script:
        - ./gradlew :webapp-smoke-test:test
    - stage: "promote to production"
      script:
        - HEROKU_API_KEY="$HEROKU_API_KEY"
        - heroku pipelines:promote -a cmh-webapp-demo-staging
    - stage: "smoke test production deployment"
      env:
        - SMOKE_TEST_ENDPOINT="https://cmh-webapp-demo.herokuapp.com"
      script:
        - ./gradlew :webapp-smoke-test:test
