language: java
jdk: openjdk8
jobs:
  include:
    - stage: build and deploy to staging
      install: echo "skip 'gradle assemble' step"
      script:
        - echo "*** BUILDING ***"
        - ./gradlew :webapp:build
        - echo "*** CREATING ARTIFACT ***"
        - ./gradlew :webapp:shadowJar
        - echo "*** DEPLOYING TO STAGING ***"
        - HEROKU_API_KEY="$HEROKU_API_KEY"
        - heroku plugins:install java
        - heroku deploy:jar webapp/build/libs/cmh-webapp-demo.jar --app cmh-webapp-demo-staging
    - stage: promote to production
      install: echo "skip 'gradle assemble' step"
      script:
        - HEROKU_API_KEY="$HEROKU_API_KEY"
        - heroku pipelines:promote -a cmh-webapp-demo-staging
