language: java
jdk: openjdk8
jobs:
  include:
    - stage: build_to_staging
      install: echo "skip 'gradle assemble' step"
      script:
        - echo "*** BUILDING ***"
        - gradle build
        - echo "*** CREATING ARTIFACT ***"
        - gradle shadowJar
        - echo "*** DEPLOYING TO STAGING ***"
        - HEROKU_API_KEY="$HEROKU_API_KEY"
        - gradle deployHeroku
    - stage: promote_to_production
      install: echo "skip 'gradle assemble' step"
      script:
        - HEROKU_API_KEY="$HEROKU_API_KEY"
        - heroku pipelines:promote -a cmh-webapp-demo-staging
